/// Symptom Translation Service
/// Loads Mbaza-translated symptom names and provides instant lookups
/// Falls back to hardcoded translations if Mbaza cache not available

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'symptom_translations_data.dart';

class SymptomTranslationsService {
  // Singleton
  static final SymptomTranslationsService _instance = SymptomTranslationsService._internal();
  factory SymptomTranslationsService() => _instance;
  SymptomTranslationsService._internal();

  // Mbaza-translated symptom names (loaded from backend cache)
  Map<String, String> _kinyarwandaMbazaTranslations = {};
  bool _isInitialized = false;

  /// Initialize with Mbaza translations from backend
  Future<void> initializeFromBackend(Map<String, String>? translations) async {
    if (translations != null) {
      _kinyarwandaMbazaTranslations = translations;
      _isInitialized = true;
      debugPrint('✅ Loaded ${translations.length} Mbaza symptom translations');
    }
  }

  /// Load from asset file (if available)
  Future<void> loadFromAssets() async {
    try {
      // Try to load pre-translated symptoms from assets
      // This file would be generated by running: npm run translate-symptoms
      // and copying the output to Flutter assets
      final String response = await rootBundle.loadString('assets/data/symptom-translations-kinyarwanda.json');
      final data = json.decode(response);
      
      if (data['translations'] != null) {
        _kinyarwandaMbazaTranslations = Map<String, String>.from(data['translations']);
        _isInitialized = true;
        debugPrint('✅ Loaded ${_kinyarwandaMbazaTranslations.length} symptom translations from assets');
      }
    } catch (e) {
      debugPrint('⚠️  Could not load symptom translations from assets: $e');
      debugPrint('   Using fallback translations');
    }
  }

  /// Get translated symptom name
  String getTranslation(String englishSymptom, Locale locale) {
    if (locale.languageCode == 'rw') {
      // Try Mbaza translations first
      if (_kinyarwandaMbazaTranslations.containsKey(englishSymptom)) {
        return _kinyarwandaMbazaTranslations[englishSymptom]!;
      }
      // Fallback to hardcoded translations
      return SymptomTranslationsData.kinyarwandaTranslations[englishSymptom] ?? englishSymptom;
    } else if (locale.languageCode == 'fr') {
      return SymptomTranslationsData.frenchTranslations[englishSymptom] ?? englishSymptom;
    }
    
    return englishSymptom; // English or unknown language
  }

  bool get isInitialized => _isInitialized;
  
  int get translationCount => _kinyarwandaMbazaTranslations.length;
}

/// Global helper function for symptom translation
String translateSymptom(String englishSymptom, Locale locale) {
  return SymptomTranslationsService().getTranslation(englishSymptom, locale);
}
