/// All symptoms supported by the ML model (132 total)
/// These match exactly with the Flask ML service symptoms
class SymptomsConstants {
  static const List<String> allSymptoms = [
    'Abdominal Pain',
    'Abnormal Menstruation',
    'Acidity',
    'Acute Liver Failure',
    'Altered Sensorium',
    'Anxiety',
    'Back Pain',
    'Belly Pain',
    'Blackheads',
    'Bladder Discomfort',
    'Blister',
    'Blood In Sputum',
    'Bloody Stool',
    'Blurred And Distorted Vision',
    'Breathlessness',
    'Brittle Nails',
    'Bruising',
    'Burning Micturition',
    'Chest Pain',
    'Chills',
    'Cold Hands And Feets',
    'Coma',
    'Congestion',
    'Constipation',
    'Continuous Feel Of Urine',
    'Continuous Sneezing',
    'Cough',
    'Cramps',
    'Dark Urine',
    'Dehydration',
    'Depression',
    'Diarrhoea',
    'Dischromic Patches',
    'Distention Of Abdomen',
    'Dizziness',
    'Drying And Tingling Lips',
    'Enlarged Thyroid',
    'Excessive Hunger',
    'Extra Marital Contacts',
    'Family History',
    'Fast Heart Rate',
    'Fatigue',
    'Fluid Overload',
    'Foul Smell Of Urine',
    'Headache',
    'High Fever',
    'Hip Joint Pain',
    'History Of Alcohol Consumption',
    'Increased Appetite',
    'Indigestion',
    'Inflammatory Nails',
    'Internal Itching',
    'Irregular Sugar Level',
    'Irritability',
    'Irritation In Anus',
    'Itching',
    'Joint Pain',
    'Knee Pain',
    'Lack Of Concentration',
    'Lethargy',
    'Loss Of Appetite',
    'Loss Of Balance',
    'Loss Of Smell',
    'Malaise',
    'Mild Fever',
    'Mood Swings',
    'Movement Stiffness',
    'Mucoid Sputum',
    'Muscle Pain',
    'Muscle Wasting',
    'Muscle Weakness',
    'Nausea',
    'Neck Pain',
    'Nodal Skin Eruptions',
    'Obesity',
    'Pain Behind The Eyes',
    'Pain During Bowel Movements',
    'Pain In Anal Region',
    'Painful Walking',
    'Palpitations',
    'Passage Of Gases',
    'Patches In Throat',
    'Phlegm',
    'Polyuria',
    'Prominent Veins On Calf',
    'Puffy Face And Eyes',
    'Pus Filled Pimples',
    'Receiving Blood Transfusion',
    'Receiving Unsterile Injections',
    'Red Sore Around Nose',
    'Red Spots Over Body',
    'Redness Of Eyes',
    'Restlessness',
    'Runny Nose',
    'Rusty Sputum',
    'Scurring',
    'Shivering',
    'Silver Like Dusting',
    'Sinus Pressure',
    'Skin Peeling',
    'Skin Rash',
    'Slurred Speech',
    'Small Dents In Nails',
    'Spinning Movements',
    'Spotting Urination',
    'Stiff Neck',
    'Stomach Bleeding',
    'Stomach Pain',
    'Sunken Eyes',
    'Sweating',
    'Swelled Lymph Nodes',
    'Swelling Joints',
    'Swelling Of Stomach',
    'Swollen Blood Vessels',
    'Swollen Extremeties',
    'Swollen Legs',
    'Throat Irritation',
    'Toxic Look (Typhos)',
    'Ulcers On Tongue',
    'Unsteadiness',
    'Visual Disturbances',
    'Vomiting',
    'Watering From Eyes',
    'Weakness In Limbs',
    'Weakness Of One Body Side',
    'Weight Gain',
    'Weight Loss',
    'Yellow Crust Ooze',
    'Yellow Urine',
    'Yellowing Of Eyes',
    'Yellowish Skin',
  ];

  /// Common symptoms (most frequently used) - for quick access
  static const List<String> commonSymptoms = [
    'Fever',
    'Cough',
    'Headache',
    'Fatigue',
    'Nausea',
    'Vomiting',
    'Diarrhea',
    'Sore Throat',
    'Shortness Of Breath',
    'Dizziness',
    'Joint Pain',
    'Muscle Ache',
    'Chills',
    'Abdominal Pain',
    'Chest Pain',
    'Loss Of Appetite',
  ];

  /// Symptoms grouped by category for better UX
  /// Each category has an icon and color for visual organization
  static const Map<String, List<String>> symptomsByCategory = {
    'General': [
      'Fatigue',
      'Malaise',
      'Lethargy',
      'Sweating',
      'Chills',
      'Shivering',
      'Weight Loss',
      'Weight Gain',
      'Dehydration',
      'High Fever',
      'Mild Fever',
      'Weakness In Limbs',
      'Muscle Weakness',
      'Muscle Wasting',
      'Loss Of Appetite',
      'Increased Appetite',
      'Excessive Hunger',
    ],
    'Respiratory': [
      'Cough',
      'Breathlessness',
      'Phlegm',
      'Congestion',
      'Runny Nose',
      'Sinus Pressure',
      'Throat Irritation',
      'Chest Pain',
      'Blood In Sputum',
      'Mucoid Sputum',
      'Rusty Sputum',
      'Patches In Throat',
      'Continuous Sneezing',
    ],
    'Digestive': [
      'Nausea',
      'Vomiting',
      'Diarrhoea',
      'Constipation',
      'Abdominal Pain',
      'Stomach Pain',
      'Belly Pain',
      'Acidity',
      'Indigestion',
      'Stomach Bleeding',
      'Bloody Stool',
      'Passage Of Gases',
      'Pain During Bowel Movements',
      'Pain In Anal Region',
      'Irritation In Anus',
      'Distention Of Abdomen',
      'Swelling Of Stomach',
    ],
    'Skin & Nails': [
      'Itching',
      'Skin Rash',
      'Skin Peeling',
      'Yellowish Skin',
      'Blister',
      'Bruising',
      'Pus Filled Pimples',
      'Blackheads',
      'Red Spots Over Body',
      'Nodal Skin Eruptions',
      'Dischromic Patches',
      'Scurring',
      'Silver Like Dusting',
      'Red Sore Around Nose',
      'Yellow Crust Ooze',
      'Brittle Nails',
      'Small Dents In Nails',
      'Inflammatory Nails',
      'Internal Itching',
    ],
    'Pain & Discomfort': [
      'Headache',
      'Back Pain',
      'Joint Pain',
      'Muscle Pain',
      'Neck Pain',
      'Chest Pain',
      'Knee Pain',
      'Hip Joint Pain',
      'Pain Behind The Eyes',
      'Cramps',
      'Painful Walking',
    ],
    'Neurological': [
      'Dizziness',
      'Loss Of Balance',
      'Unsteadiness',
      'Spinning Movements',
      'Slurred Speech',
      'Loss Of Smell',
      'Altered Sensorium',
      'Lack Of Concentration',
      'Coma',
      'Stiff Neck',
      'Movement Stiffness',
      'Swelling Joints',
      'Weakness Of One Body Side',
      'Toxic Look (Typhos)',
    ],
    'Eyes & Vision': [
      'Redness Of Eyes',
      'Yellowing Of Eyes',
      'Watering From Eyes',
      'Sunken Eyes',
      'Blurred And Distorted Vision',
      'Visual Disturbances',
      'Pain Behind The Eyes',
      'Puffy Face And Eyes',
    ],
    'Urinary': [
      'Burning Micturition',
      'Dark Urine',
      'Yellow Urine',
      'Bladder Discomfort',
      'Continuous Feel Of Urine',
      'Polyuria',
      'Foul Smell Of Urine',
      'Spotting Urination',
    ],
    'Cardiovascular': [
      'Fast Heart Rate',
      'Palpitations',
      'Chest Pain',
      'Swollen Legs',
      'Swollen Blood Vessels',
      'Prominent Veins On Calf',
      'Swollen Extremeties',
    ],
    'Mental & Behavioral': [
      'Anxiety',
      'Depression',
      'Mood Swings',
      'Restlessness',
      'Irritability',
      'Cold Hands And Feets',
    ],
    'Liver & Digestive System': [
      'Yellowish Skin',
      'Yellowing Of Eyes',
      'Dark Urine',
      'Acute Liver Failure',
      'Fluid Overload',
      'Swelling Of Stomach',
      'Distention Of Abdomen',
      'History Of Alcohol Consumption',
    ],
    'Throat & Mouth': [
      'Throat Irritation',
      'Patches In Throat',
      'Ulcers On Tongue',
      'Drying And Tingling Lips',
    ],
    'Endocrine & Metabolic': [
      'Enlarged Thyroid',
      'Irregular Sugar Level',
      'Obesity',
      'Weight Gain',
      'Weight Loss',
      'Excessive Hunger',
      'Increased Appetite',
      'Polyuria',
    ],
    'Other': [
      'Swelled Lymph Nodes',
      'Receiving Blood Transfusion',
      'Receiving Unsterile Injections',
      'Family History',
      'Extra Marital Contacts',
      'Abnormal Menstruation',
    ],
  };

  /// Category metadata for UI display
  static const Map<String, Map<String, dynamic>> categoryMetadata = {
    'General': {'icon': 'thermostat', 'color': 0xFFE57373},
    'Respiratory': {'icon': 'air', 'color': 0xFF64B5F6},
    'Digestive': {'icon': 'restaurant', 'color': 0xFF81C784},
    'Skin & Nails': {'icon': 'face', 'color': 0xFFFFB74D},
    'Pain & Discomfort': {'icon': 'healing', 'color': 0xFFBA68C8},
    'Neurological': {'icon': 'psychology', 'color': 0xFF9575CD},
    'Eyes & Vision': {'icon': 'visibility', 'color': 0xFF4FC3F7},
    'Urinary': {'icon': 'water_drop', 'color': 0xFF4DD0E1},
    'Cardiovascular': {'icon': 'favorite', 'color': 0xFFE91E63},
    'Mental & Behavioral': {'icon': 'mood', 'color': 0xFF7986CB},
    'Liver & Digestive System': {'icon': 'biotech', 'color': 0xFFA1887F},
    'Throat & Mouth': {'icon': 'record_voice_over', 'color': 0xFF90CAF9},
    'Endocrine & Metabolic': {'icon': 'science', 'color': 0xFFAED581},
    'Other': {'icon': 'more_horiz', 'color': 0xFF90A4AE},
  };
}
